name: Grype It

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  grype-it-up:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Scan Root
        uses: anchore/scan-action@v2
        with:
          path: "."
