name: Security Jobs

on:
  push:
    branches:
      - feat/grype-workflow
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  syft:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: generate-sbom
        uses: anchore/sbom-action@v0
        with:
          path: "."
          artifact-name: weather-sbom.spdx
  grype-it-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Scan Root
        uses: anchore/scan-action@v7
        with:
          path: "."
    permissions:
      contents: read

